# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pigeon < Formula
  desc "Local email client for the terminal"
  homepage "https://github.com/tomowang/pigeoncli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomowang/pigeoncli/releases/download/v0.2.0/pigeoncli_0.2.0_darwin_amd64.tar.gz"
      sha256 "779d933cd0df154289c646b1f53042bc1eada18cf7536fb7433fec59e666027e"

      define_method(:install) do
        bin.install "pigeon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomowang/pigeoncli/releases/download/v0.2.0/pigeoncli_0.2.0_darwin_arm64.tar.gz"
      sha256 "08e7d7305e32e87e56dcb8e2bacfb6c0546f7e02fce7cb7353884f912a9e8e46"

      define_method(:install) do
        bin.install "pigeon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomowang/pigeoncli/releases/download/v0.2.0/pigeoncli_0.2.0_linux_amd64.tar.gz"
      sha256 "aa76f0334bc592f3ce502d3ddf74adbed58e9a3c743292900165b23d53723cc3"
      define_method(:install) do
        bin.install "pigeon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomowang/pigeoncli/releases/download/v0.2.0/pigeoncli_0.2.0_linux_arm64.tar.gz"
      sha256 "bc61fda2540eeb8fbbb03234fc6164a12cf3be3ed4ab042536a892d699f804ee"
      define_method(:install) do
        bin.install "pigeon"
      end
    end
  end

  test do
    system "#{bin}/pigeon", "version"
  end
end
