# This file was generated by GoReleaser. DO NOT EDIT.
cask "pigeon" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "e319a32bee2311853f7fca5c487cf9706b54d6c3747b9d841efa222d6706a710"
      url "https://github.com/tomowang/pigeoncli/releases/download/v#{version}/pigeoncli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c076e62cb01cde6c0634faab1bc96d4333b8b62aa5042c64b2684cd921b8529f"
      url "https://github.com/tomowang/pigeoncli/releases/download/v#{version}/pigeoncli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a3d3fbacee9772caf3105754413548bd92e8f5c20915f4374f751dd19ec1b18b"
      url "https://github.com/tomowang/pigeoncli/releases/download/v#{version}/pigeoncli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af436056b9ccda6aaafeda840e3b6a99a2a0eccc6d1ed32cd04d8d1cce5eea4e"
      url "https://github.com/tomowang/pigeoncli/releases/download/v#{version}/pigeoncli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pigeon"
  desc "Local email client for the terminal"
  homepage "https://github.com/tomowang/pigeoncli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pigeon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/pigeon"]
    end
  end

  # No zap stanza required
end
